# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#             TMUX Keybindings - Core            ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Change prefix from 'Ctrl+B' to 'Ctrl+A'
unbind C-b
bind-key C-a send-prefix

bind-key B set status # Hide or Reveal status bar

# Maximizing and minimizing tmux pane
bind -r m resize-pane -Z

# Kill windows and session
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt (cmd+w)
bind-key C-x kill-session

# Reloading tmux
unbind R
bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded TMUX Configuration!"

# Rename Window
bind r command-prompt "rename-window %%"

# Window Management
bind-key c new-window       # <prefix> c to create a new window
bind-key n next-window      # <prefix> n to move to next window
bind-key p previous-window  # <prefix> p to move to previous window

# Session Management
bind-key C choose-session   # <prefix> C to choose a session
bind-key N switch-client -n # <prefix> N to move to next session
bind-key P switch-client -p # <prefix> P to move to previous session

# New bindings for spliting windows using | and -
unbind '"'
unbind %
bind - split-window -v -c "#{pane_current_path}"
bind = split-window -h -c "#{pane_current_path}"

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#           TMUX Keybindings - Advanced          ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# bind-key -T copy-mode-vi 'C-h' select-pane -L
# bind-key -T copy-mode-vi 'C-j' select-pane -D
# bind-key -T copy-mode-vi 'C-k' select-pane -U
# bind-key -T copy-mode-vi 'C-l' select-pane -R
# bind-key -T copy-mode-vi 'v' send-keys -X begin-selection

# Switch panes while in copy mode
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\\ select-pane -l # Tabs, but for panes

# pbcopy is Mac-specific
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle \; send -X begin-selection "pbcopy"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃              Configuration Hint              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Use: tmux list-keys | less
# C- for control key; M- for alt/option key; S- for shift key;