#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=on
	ax_focus=on
	order=below
	active_color=0xffe2e2e3
	inactive_color=0x662c2e34
	background_color=0x00000000
	blacklist="Finder,Notification Center,Dock,Control Center,System Settings,Launchpad"
)

borders "${options[@]}"
