#!/bin/bash

options=(
  style=round
  width=3.0
  hidpi=on
  ax_focus=on
  order=above
  active_color=0xff45475a
  inactive_color=0x662c2e34
  background_color=0x00000000
  blacklist="Finder,Notification Center,Dock,Control Center,System Settings,Launchpad"
)

borders "${options[@]}"
