# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                   Theme 01                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

set -g mode-style "bg=default,fg=default"
set -g @emulate-scroll-for-no-mouse-alternate-buffer on

set -g status-justify centre
set -g status-left "#[fg=black,bg=green]   #[fg=green,bg=red]#{prefix_highlight}#[bg=default]"
set -g window-status-format "#[fg=magenta,bg=black] #I:#W #[bg=default,fg=black]"
set -g window-status-current-format "#[bg=magenta,fg=black] #I:#W#{?window_zoomed_flag, ,} #[bg=default,fg=black] #[bg=black,fg=red] #S #[bg=red,fg=black]   "
set -g status-right "#[bg=black,fg=green] %I:%M %p #[fg=green,bg=black]█"

set -g status-bg default
set -g status-fg white
set -g status-style "fg=white,bg=default"

set -g @prefix_highlight_prefix_prompt "MOD"
set -g @prefix_highlight_copy_prompt "COPY"
set -g @prefix_highlight_sync_prompt " "
set -g @prefix_highlight_bg "black"
set -g @prefix_highlight_fg "red"
set -g @prefix_highlight_empty_attr "fg=black,bg=red"
set -g @prefix_highlight_copy_mode_attr "fg=blue,bg=black"
set -g @prefix_highlight_sync_mode_attr "fg=black,bg=green"
set -g @prefix_highlight_show_copy_mode on
set -g @prefix_highlight_show_sync_mode on
set -g @prefix_highlight_empty_has_affixes off
set -g @prefix_highlight_output_prefix ""
set -g @prefix_highlight_output_suffix ""
set -g @prefix_highlight_empty_prompt ""

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                   Theme 02                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

set -g @plugin 'catppuccin/tmux' # catppuccin config
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "host date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{pane_current_path}"
set -g @catppuccin_date_time_text "%I:%M %p"
set -g status-bg default
set -g status-style bg=default